import type { Metadata } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import { Providers } from '@/components/provider';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const jetBrains_Mono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body className={`${jetBrains_Mono.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
